### ISSUE TITLE
Issue with line wrap?

### ISSUE THREAD

**Issue by ThisIsJeron** [markpanado/HYPERBEAST#1]
After typing a command longer than 4 characters, the line wrap goes to the start of the line and overwrites the prompt...

<img width="570" alt="screenshot at sep 21 12-59-37" src="https://user-images.githubusercontent.com/14175797/30715927-e83544e4-9ecc-11e7-93cf-29fc3a47dcaf.png">
<img width="575" alt="screenshot at sep 21 13-00-05" src="https://user-images.githubusercontent.com/14175797/30715928-e837bef4-9ecc-11e7-8260-e2d3c4b373e4.png">
<img width="569" alt="screenshot at sep 21 13-00-42" src="https://user-images.githubusercontent.com/14175797/30715926-e819b09e-9ecc-11e7-8853-d56e7b9ede23.png">

.bash_profile looks like this: 
```
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export PATH=$PATH:$(go env GOPATH)/bin

# Setting PATH for Python 3.5
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

##
# Your previous /Users/jeron/.bash_profile file was backed up as /Users/jeron/.bash_profile.macports-saved_2017-09-02_at_04:15:57
##

# MacPorts Installer addition on 2017-09-02_at_04:15:57: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

# COLORS
KMAG='\e[0;35m'
KRED='\033[0;31m'
KWHT='\e[97m'
KNC='\033[0m'
KOR='\e[5;95;38;5;214m'
KBL='\e[0;36m'

# BACKGROUND COLORS
KBGDEF='\e[49m'
KBGRED='\e[41m'

# FONT STYLES
KFDEF='\e[0m'
KFBOLD='\e[1m'
KFITALIC='\e[3m'

# If you want to remove the current path
# export PS1="${KMAG}▲${KNC} ${KBGRED}${KWHT}${KFBOLD}${KFITALIC} Supreme ${KFDEF}${KNC}${KBGDEF} "

# With current path
export PS1="${KMAG}▲${KNC} ${KOR}\w${KNC} ${KBGRED}${KWHT}${KFBOLD}${KFITALIC} Supreme ${KFDEF}${KNC}${KBGDEF} "
```

**Comment by markpanado** [comment]
Thank you reporting the issue. Do you have Hyper terminal (http://hyper.is)? That's what I'm using for this repo. I will try to replicate this and will get back to you.

**Comment by ThisIsJeron** [comment]
I'm using iTerm, however I was able to replicate the issue on default Mac
terminal as well.

**Comment by markpanado** [comment]
Issue is now fixed. Thanks to @nbabra for the fix.
